# see https://github.com/carlynorama/SwiftLIBPNG/blob/main/.github/workflows/swift_linux.yml
name: Swift, Latest Ubuntu, Container

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
           swift build -v
      - name: Test
        run: |
            swift test -v